# Generated by Django 3.2.4 on 2022-11-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=30)),
                ('f2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ChildClass1',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.baseclass')),
                ('f3', models.CharField(max_length=30)),
                ('f4', models.CharField(max_length=30)),
            ],
            bases=('testapp.baseclass',),
        ),
        migrations.CreateModel(
            name='ChildClass2',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.baseclass')),
                ('f5', models.IntegerField()),
            ],
            bases=('testapp.baseclass',),
        ),
    ]
